version: '3'

services:

  # Name of the service
  broker-service:
    # Path to the Dockerfile
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    # Restart policy (always, unless-stopped, on-failure)
    restart: always
    # Port mapping (map port 8080 on our local machine to port 80 in the container)
    ports:
      - "8080:80"
    # Deploy only one instance of the service
    deploy:
      mode: replicated
      replicas: 1

